[package]
name = "amdgpu-fanc"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
strip = true

[build-dependencies]
cc = "1.0.73"

[dependencies]
clap = { version = "3.2.16", features = ["cargo", "derive"] }

